### ISSUE TITLE
list_deposit_addresses function does not have a limit and offset params

### ISSUE THREAD

**Issue by likem3** [Crypto-APIs/Crypto_APIs_2.0_SDK_Python#1]
https://github.com/Crypto-APIs/Crypto_APIs_2.0_SDK_Python/blob/5b3d5f0dbd3fa1d4904bbfc9d4c424b690175346/cryptoapis/api/informative_api.py#L1157C5-L1163C7

In the API documentation [here](https://developers.cryptoapis.io/technical-documentation/api/wallet-as-a-service/informative/list-deposit-addresses) there are query parameters available for offset and limit.

Is there any method to send offset and limit from the API SDK?

**Comment by Crypto-APIs** [comment]
Hello,

Thank you for reporting to us, the issue has been resolved in [v1.8.0](https://pypi.org/project/cryptoapis/1.8.0/).

Kind regards,
Crypto APIs Team
